import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#b70011",
          foreground: "#ffffff",
          hover: "#b91c1c",
        },
        "primary-container": "#dc2626",
        "racing-red-hover": "#b91c1c",
        "on-primary-container": "#ffffff",
        background: "#ffffff",
        surface: "#f8fafc",
        "surface-card": "#ffffff",
        "surface-elevated": "#ffffff",
        "surface-canvas": "#ffffff",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-low": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0f172a",
        secondary: "#64748b",
        "on-secondary": "#ffffff",
        "status-success": "#10B981",
        "border-subtle": "#e2e8f0",
        "border-strong": "#cbd5e1",
        foreground: "#0f172a",
        muted: {
          DEFAULT: "#f8fafc",
          foreground: "#64748b",
        },
        border: "#e2e8f0",
        card: {
          DEFAULT: "#ffffff",
          foreground: "#0f172a",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        margin: "3rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "system-ui", "sans-serif"],
        display: ["var(--font-barlow)", "system-ui", "sans-serif"],
        "headline-sm": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "headline-xl-mobile": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "display-hero-mobile": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "label-md": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "label-numeric-lg": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "body-sm": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "display-hero": ["var(--font-barlow)", "system-ui", "sans-serif"],
        caption: ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "label-numeric-md": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "headline-xl": ["var(--font-barlow)", "system-ui", "sans-serif"],
        "label-caps": ["var(--font-barlow)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl-mobile": ["34px", { lineHeight: "38px", letterSpacing: "0.01em", fontWeight: "700" }],
        "display-hero-mobile": ["44px", { lineHeight: "48px", letterSpacing: "0.02em", fontWeight: "800" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-numeric-lg": ["28px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero": ["72px", { lineHeight: "76px", letterSpacing: "0.02em", fontWeight: "800" }],
        caption: ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "label-numeric-md": ["20px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "36px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "0.01em", fontWeight: "700" }],
        "label-caps": ["14px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "700" }],
      },
      maxWidth: {
        site: "1320px",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        fadeIn: "fadeIn 300ms ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
